<a href="https://colab.research.google.com/github/rajjjxd/ML-Tutorials/blob/main/Ordinal_Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
df = pd.read_csv('customer.csv')
df.sample(5)

age  gender   review education purchased
5    31  Female  Average    School       Yes
39   76    Male     Poor        PG        No
46   64  Female     Poor        PG        No
36   34  Female     Good        UG       Yes
4    16  Female  Average        UG        No

In [ ]:
df


age  gender   review education purchased
0    30  Female  Average    School        No
1    68  Female     Poor        UG        No
2    70  Female     Good        PG        No
3    72  Female     Good        PG        No
4    16  Female  Average        UG        No
5    31  Female  Average    School       Yes
6    18    Male     Good    School        No
7    60  Female     Poor    School       Yes
8    65  Female  Average        UG        No
9    74    Male     Good        UG       Yes
10   98  Female     Good        UG       Yes
11   74    Male     Good        UG       Yes
12   51    Male     Poor    School        No
13   57  Female  Average    School        No
14   15    Male     Poor        PG       Yes
15   75    Male     Poor        UG        No
16   59    Male     Poor        UG       Yes
17   22  Female     Poor        UG       Yes
18   19    Male     Good    School        No
19   97    Male     Poor        PG       Yes
20   57  Female  Average    School       Yes
21   32    Male  Average        PG        No
22   18  Female     Poor        PG       Yes
23   96  Female     Good    School        No
24   16  Female  Average        PG       Yes
25   57  Female     Good    School        No
26   53  Female     Poor        PG        No
27   69  Female     Poor        PG        No
28   48    Male     Poor    School        No
29   83  Female  Average        UG       Yes
30   73    Male  Average        UG        No
31   22  Female     Poor    School       Yes
32   92    Male  Average        UG       Yes
33   89  Female     Good        PG       Yes
34   86    Male  Average    School        No
35   74    Male     Poor    School       Yes
36   34  Female     Good        UG       Yes
37   94    Male  Average        PG       Yes
38   45  Female     Good    School        No
39   76    Male     Poor        PG        No
40   39    Male     Good    School        No
41   23    Male     Good        PG       Yes
42   30  Female     Good        PG       Yes
43   27    Male     Poor        PG        No
44   77  Female  Average        UG        No
45   61    Male     Poor        PG       Yes
46   64  Female     Poor        PG        No
47   38  Female     Good        PG       Yes
48   39  Female     Good        UG       Yes
49   25  Female     Good        UG        No

In [ ]:
df = df.iloc[:,2:]

In [ ]:
df


review education purchased
0   Average    School        No
1      Poor        UG        No
2      Good        PG        No
3      Good        PG        No
4   Average        UG        No
5   Average    School       Yes
6      Good    School        No
7      Poor    School       Yes
8   Average        UG        No
9      Good        UG       Yes
10     Good        UG       Yes
11     Good        UG       Yes
12     Poor    School        No
13  Average    School        No
14     Poor        PG       Yes
15     Poor        UG        No
16     Poor        UG       Yes
17     Poor        UG       Yes
18     Good    School        No
19     Poor        PG       Yes
20  Average    School       Yes
21  Average        PG        No
22     Poor        PG       Yes
23     Good    School        No
24  Average        PG       Yes
25     Good    School        No
26     Poor        PG        No
27     Poor        PG        No
28     Poor    School        No
29  Average        UG       Yes
30  Average        UG        No
31     Poor    School       Yes
32  Average        UG       Yes
33     Good        PG       Yes
34  Average    School        No
35     Poor    School       Yes
36     Good        UG       Yes
37  Average        PG       Yes
38     Good    School        No
39     Poor        PG        No
40     Good    School        No
41     Good        PG       Yes
42     Good        PG       Yes
43     Poor        PG        No
44  Average        UG        No
45     Poor        PG       Yes
46     Poor        PG        No
47     Good        PG       Yes
48     Good        UG       Yes
49     Good        UG        No

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:2] ,df.iloc[:,-1], test_size=0.2)



In [ ]:
X_train


review education
24  Average        PG
31     Poor    School
0   Average    School
23     Good    School
13  Average    School
11     Good        UG
38     Good    School
25     Good    School
9      Good        UG
3      Good        PG
14     Poor        PG
2      Good        PG
49     Good        UG
39     Poor        PG
4   Average        UG
40     Good    School
15     Poor        UG
45     Poor        PG
5   Average    School
47     Good        PG
43     Poor        PG
7      Poor    School
34  Average    School
8   Average        UG
36     Good        UG
16     Poor        UG
18     Good    School
21  Average        PG
32  Average        UG
41     Good        PG
17     Poor        UG
44  Average        UG
30  Average        UG
19     Poor        PG
33     Good        PG
37  Average        PG
10     Good        UG
46     Poor        PG
28     Poor    School
1      Poor        UG

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [ ]:
 X_train = oe.transform(X_train)
 X_test = oe.transform(X_test)

In [ ]:
X_train


array([[1., 2.],
       [0., 0.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [2., 1.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [1., 1.],
       [2., 0.],
       [0., 1.],
       [0., 2.],
       [1., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [0., 1.],
       [2., 0.],
       [1., 2.],
       [1., 1.],
       [2., 2.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [1., 2.],
       [2., 1.],
       [0., 2.],
       [0., 0.],
       [0., 1.]])

In [ ]:
X_test

array([[2., 2.],
       [2., 1.],
       [0., 0.],
       [0., 2.],
       [0., 0.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [1., 0.],
       [2., 0.]])

In [ ]:
# now we'll do the label encoding(random order decide)

In [ ]:
from sklearn.preprocessing import LabelEncoder


In [ ]:
le = LabelEncoder()


In [ ]:
le.fit(y_train)


LabelEncoder()

In [ ]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [ ]:
y_train

array([1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0])